# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datasets',
            new_name='Dataset',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
