# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_checker', '0004_auto_20171130_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='json_file',
            field=models.FileField(default='documents/None/No-doc.json', upload_to='documents/'),
        ),
    ]
